// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb_7kdTv1sBr9L0Oii1xAizo4ICsCNK-k',
    appId: '1:53404183582:web:3870377fb248b1e8e8920f',
    messagingSenderId: '53404183582',
    projectId: 'chatting-2219',
    authDomain: 'chatting-2219.firebaseapp.com',
    storageBucket: 'chatting-2219.appspot.com',
    measurementId: 'G-H2FMCG66W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMghG1w0X7QYp3j4CrFdGFdcXQber0fTY',
    appId: '1:53404183582:android:2ea7f868d8f038a0e8920f',
    messagingSenderId: '53404183582',
    projectId: 'chatting-2219',
    storageBucket: 'chatting-2219.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAADHmgEByhhLnQZAwJJzwWjLhSYTaVZ8s',
    appId: '1:53404183582:ios:9f351fb0dd4f6f40e8920f',
    messagingSenderId: '53404183582',
    projectId: 'chatting-2219',
    storageBucket: 'chatting-2219.appspot.com',
    iosClientId: '53404183582-n3f0qd6tmq1tk6cm2b6r8jhdt31m3ikh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingStarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAADHmgEByhhLnQZAwJJzwWjLhSYTaVZ8s',
    appId: '1:53404183582:ios:9f351fb0dd4f6f40e8920f',
    messagingSenderId: '53404183582',
    projectId: 'chatting-2219',
    storageBucket: 'chatting-2219.appspot.com',
    iosClientId: '53404183582-n3f0qd6tmq1tk6cm2b6r8jhdt31m3ikh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingStarter',
  );
}
